

version: '3.8'

services:
  api1:
    build:
      context: ./drushim_project/drushim
      dockerfile: Dockerfile
      args:
      http_proxy : http://10.9.5.141:8080/
      https_proxy : http://10.9.5.141:8080/
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - TARGET_API_URL=${ADAM_API_URL}
    networks:
      - internalnet

  api2:
    build:
      context: ./SimiltaryWorlds/SimiltaryWorlds
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - TARGET_API_URL=${AI_API_URL}
    networks:
      - internalnet

  pythonapi:
    build:
      context: ./drushim_pro
      dockerfile: Dockerfile
    ports:
      - "5003:5000"
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge

